version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Get model data....
      - mkdir -p flask_app/models
      - cp -r $CODEBUILD_SRC_DIR_model/* flask_app/models/
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME/$SERVICE_NAME:$CODEBUILD_BUILD_NUMBER flask_app/.
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME/$SERVICE_NAME:$CODEBUILD_BUILD_NUMBER
      - printf '[{"name":"%s","imageUri":"%s/%s:%s"}]' $CONTAINER_NAME $IMAGE_REPO_NAME $SERVICE_NAME $CODEBUILD_BUILD_NUMBER > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

